# Tasks required for setting Plack
- name: Enable Plack
  shell: koha-plack --enable {{ koha_instance_name }} > /dev/null 2>&1 || /bin/true
  ignore_errors: yes

- name: Start Plack
  shell:  koha-plack --start {{ koha_instance_name }} > /dev/null 2>&1 || /bin/true
  notify: restart apache
  ignore_errors: yes
